### ISSUE TITLE
Installation failure

### ISSUE THREAD

**Issue by mackensen** [Swarthmore/filescan-server#2]
Node version: `v0.10.25`

When attempting to run `npm start` after running `npm install`:

``` bash
/var/www/filescan/controllers/FileService.js:2
let	PDFParser = require("pdf2json"),
^^^
Error initializing middleware
SyntaxError: Unexpected strict mode reserved word
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/var/www/filescan/controllers/File.js:5:12)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
npm ERR! weird error 1
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

npm ERR! not ok code 0
```

**Comment by aruethe2** [comment]
Looks like a node.js version issue.  I'm on v6.9.1.  I'll check to see what the minimum requirement is and post it  in the README.

**Comment by aruethe2** [comment]
@mackensen suggests moving to a separate folder in the plugin with a note stating the version of Guzzle used.

**Comment by mackensen** [comment]
Confirmed that bumping nodejs to something a little less primitive resolved the issue. For me that was `v8.1.2`.
